server {
    listen 80;
    # Utilise un vrai sous-domaine (ex: updates.ethernanos.space)
    server_name updates.ethernanos.space; 

    # Redirection automatique vers le HTTPS (une fois le certificat généré)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl; # Certbot ajoutera les lignes SSL automatiquement
    server_name updates.ethernanos.space;

    # Chemin vers tes releases sur le VPS
    root /home/stech/launcher; 

    # Gérer les Releases du Hubtefv
    location /releases/ {
        alias /home/stech/launcher/releases/;
        add_header Access-Control-Allow-Origin *; # Crucial pour le Hub Rust
        add_header Cache-Control "no-cache";
        autoindex on; # Utile pour voir les fichiers dans le navigateur
    }

    # Optimisation pour les gros fichiers (EXE, MSI, DEB)
    location ~* \.(msi|exe|dmg|deb|AppImage|tar\.gz)$ {
        root /home/stech/launcher; # Utilise root ici pour matcher le chemin
        sendfile on;
        tcp_nopush on;
        types {
            application/octet-stream msi exe dmg deb AppImage;
        }
    }

    access_log /var/log/nginx/launcher_updates_access.log;
    error_log /var/log/nginx/launcher_updates_error.log;
}